function [ alpha_0 ] = GSL_LP_stepsize_instant_ts(ldp, ...
    beta_0,...
    FW_beta_direction,...
    l_matrix,...
    eig_tol,...
    L_beta,...
    data_label,...
    n_beta,...
    GD_NR, ...
    beta_p_const)
% step 1: check first derivatives at 0 and 1

% check first derivative at 0
alpha_0=0;
% lambda_FW_alpha_0=(beta_0+alpha_0*(FW_beta_direction-beta_0)).*l_matrix+eig_tol; % N x P
% lambda_FW_alpha=(FW_beta_direction-beta_0).*l_matrix; % N x P
[lambda_FW_alpha_0,lambda_FW_alpha] = lambda_FW_alpha_compute(...
    beta_0, ...
    alpha_0, ...
    FW_beta_direction, ...
    l_matrix, ...
    eig_tol);

[ f_alpha_first_00,f_alpha_second_00 ] = ...
    first_second_alpha_derivative_instant(ldp, ...
    L_beta,...
    data_label,...
    FW_beta_direction,...
    lambda_FW_alpha_0,...
    lambda_FW_alpha,...
    beta_0,...
    l_matrix,...
    n_beta, ...
    beta_p_const);
f_alpha_first1=f_alpha_first_00;

% check first derivative at 1
alpha_0=1;
% lambda_FW_alpha_0=(beta_0+alpha_0*(FW_beta_direction-beta_0)).*l_matrix+eig_tol; % N x P
% lambda_FW_alpha=(FW_beta_direction-beta_0).*l_matrix; % N x P
[lambda_FW_alpha_0,lambda_FW_alpha] = lambda_FW_alpha_compute(...
    beta_0, ...
    alpha_0, ...
    FW_beta_direction, ...
    l_matrix, ...
    eig_tol);

[ f_alpha_first_11,f_alpha_second_11 ] = ...
    first_second_alpha_derivative_instant(ldp, ...
    L_beta,...
    data_label,...
    FW_beta_direction,...
    lambda_FW_alpha_0,...
    lambda_FW_alpha,...
    beta_0,...
    l_matrix,...
    n_beta, ...
    beta_p_const);
f_alpha_first2=f_alpha_first_11;

if f_alpha_first1>=0 && f_alpha_first2>0
    alpha_0=0;
elseif f_alpha_first1<0 && f_alpha_first2<=0
    alpha_0=1;
else

    %2023-10-11-start

    %2023-10-11-end

    if GD_NR==1
        gL=0;
        gU=1;
        nn=0;
        tol_GD=1e-5;
        while abs(gL-gU)>tol_GD
            nn=nn+1;
            alpha_0=(gL+gU)/2;
            lambda_FW_alpha_0=(beta_0+alpha_0*(FW_beta_direction-beta_0)).*l_matrix+eig_tol; % N x P
            [ G_gM,~ ] = ...
                first_second_alpha_derivative_instant(ldp, ...
                L_beta,...
                data_label,...
                FW_beta_direction,...
                lambda_FW_alpha_0,...
                lambda_FW_alpha,...
                beta_0,...
                l_matrix,...
                n_beta, ...
                beta_p_const);
            if G_gM>0 % fmin=f(gamma\in[gL,gamma])
                gU=alpha_0;
            elseif G_gM<0 % fmin=f(gamma\in[gamma,gU])
                gL=alpha_0;
            else % G_gM=0
                %gamma=gM;
                break
            end
        end
    else

        alpha_0=0.5;
        delta_alpha=Inf;
        count=1;
        while delta_alpha>1e-5
            %             lambda_FW_alpha_0=(beta_0+alpha_0*(FW_beta_direction-beta_0)).*l_matrix+eig_tol; % N x P
            %             lambda_FW_alpha=(FW_beta_direction-beta_0).*l_matrix; % N x P
            [lambda_FW_alpha_0,lambda_FW_alpha] = lambda_FW_alpha_compute(...
                beta_0, ...
                alpha_0, ...
                FW_beta_direction, ...
                l_matrix, ...
                eig_tol);

            [ f_alpha_first,f_alpha_second ] = ...
                first_second_alpha_derivative_instant(ldp, ...
                L_beta,...
                data_label,...
                FW_beta_direction,...
                lambda_FW_alpha_0,...
                lambda_FW_alpha,...
                beta_0,...
                l_matrix,...
                n_beta, ...
                beta_p_const);

            if f_alpha_second==0
                gL=0;
                gU=1;
                nn=0;
                tol_GD=1e-5;
                while abs(gL-gU)>tol_GD
                    nn=nn+1;
                    alpha_0=(gL+gU)/2;
                    lambda_FW_alpha_0=(beta_0+alpha_0*(FW_beta_direction-beta_0)).*l_matrix+eig_tol; % N x P
                    [ G_gM,~ ] = ...
                        first_second_alpha_derivative_instant(ldp, ...
                        L_beta,...
                        data_label,...
                        FW_beta_direction,...
                        lambda_FW_alpha_0,...
                        lambda_FW_alpha,...
                        beta_0,...
                        l_matrix,...
                        n_beta, ...
                        beta_p_const);
                    if G_gM>0 % fmin=f(gamma\in[gL,gamma])
                        gU=alpha_0;
                    elseif G_gM<0 % fmin=f(gamma\in[gamma,gU])
                        gL=alpha_0;
                    else % G_gM=0
                        %gamma=gM;
                        break
                    end
                end
                break
            end
            alpha_current=alpha_0-(f_alpha_first/f_alpha_second);
            if alpha_current>1
                if count==1
                    alpha_current=1;
                else
                    alpha_0=1;
                    break
                end
            elseif alpha_current<0
                if count==1
                    alpha_current=0;
                else
                    alpha_0=0;
                    break
                end
            end
            delta_alpha=norm(alpha_current-alpha_0);
            alpha_0=alpha_current;
            count=count+1;
        end
    end
end
end

